#!/bin/bash

# Installation script for automated log rotation cron job
# Sets up cron job to run log rotation automatically

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROTATE_SCRIPT="$SCRIPT_DIR/rotate-logs.sh"

# Source logging utilities if available
if [[ -f "$SCRIPT_DIR/logging-utils.sh" ]]; then
    source "$SCRIPT_DIR/logging-utils.sh"
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Default configuration
CRON_SCHEDULE="${GOOSE_CRON_SCHEDULE:-0 2 * * *}"  # Daily at 2 AM
INSTALL_TYPE="${GOOSE_CRON_INSTALL_TYPE:-user}"   # user or system
CRON_LOG_DIR="${GOOSE_CRON_LOG_DIR:-/tmp/goose-logs}"
CRON_LOG_FILE="$CRON_LOG_DIR/cron-rotation.log"

# Function to detect OS
detect_os() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "macos"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "linux"
    else
        echo "unknown"
    fi
}

# Function to check if script exists and is executable
check_rotate_script() {
    if [[ ! -f "$ROTATE_SCRIPT" ]]; then
        print_error "Log rotation script not found: $ROTATE_SCRIPT"
        exit 1
    fi
    
    if [[ ! -x "$ROTATE_SCRIPT" ]]; then
        print_warning "Making rotation script executable..."
        chmod +x "$ROTATE_SCRIPT"
    fi
}

# Function to get absolute path
get_absolute_path() {
    local path="$1"
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        readlink -f "$path" 2>/dev/null || python3 -c "import os; print(os.path.realpath('$path'))"
    else
        # Linux
        readlink -f "$path"
    fi
}

# Function to create cron wrapper script
create_cron_wrapper() {
    local wrapper_dir="$SCRIPT_DIR"
    local wrapper_file="$wrapper_dir/cron-rotate-logs-wrapper.sh"
    local abs_rotate_script
    abs_rotate_script=$(get_absolute_path "$ROTATE_SCRIPT")
    
    # Create log directory
    mkdir -p "$CRON_LOG_DIR"
    
    cat > "$wrapper_file" <<EOF
#!/bin/bash
# Wrapper script for cron log rotation
# Generated by install-cron-log-rotation.sh
# Do not edit manually - regenerated on each installation

# Set PATH to include common locations
export PATH="/usr/local/bin:/usr/bin:/bin:\$PATH"

# Set environment variables
export LOG_DIR="${LOG_DIR:-/tmp/goose-logs}"
export GOOSE_LOG_DETAILED_RETENTION_DAYS="${GOOSE_LOG_DETAILED_RETENTION_DAYS:-7}"
export GOOSE_LOG_SUMMARY_RETENTION_DAYS="${GOOSE_LOG_SUMMARY_RETENTION_DAYS:-30}"
export GOOSE_LOG_ARCHIVE_RETENTION_DAYS="${GOOSE_LOG_ARCHIVE_RETENTION_DAYS:-365}"
export GOOSE_LOG_COMPRESS_AFTER_DAYS="${GOOSE_LOG_COMPRESS_AFTER_DAYS:-7}"
export GOOSE_LOG_MAX_SIZE_MB="${GOOSE_LOG_MAX_SIZE_MB:-100}"

# Set timezone (use system default)
export TZ="\$(date +%Z)"

# Log file for cron output
LOG_FILE="$CRON_LOG_FILE"
mkdir -p "\$(dirname "\$LOG_FILE")"

# Redirect stdout and stderr to log file
exec >> "\$LOG_FILE" 2>&1

# Log execution start
echo "=== Cron log rotation started at \$(date) ==="

# Run the rotation script
"$abs_rotate_script"

# Log execution end
EXIT_CODE=\$?
if [[ \$EXIT_CODE -eq 0 ]]; then
    echo "=== Cron log rotation completed successfully at \$(date) ==="
else
    echo "=== Cron log rotation failed with exit code \$EXIT_CODE at \$(date) ==="
fi

exit \$EXIT_CODE
EOF

    chmod +x "$wrapper_file"
    echo "$wrapper_file"
}

# Function to install user-level cron
install_user_cron() {
    local wrapper_script="$1"
    local abs_wrapper_script
    abs_wrapper_script=$(get_absolute_path "$wrapper_script")
    
    print_info "Installing user-level cron job..."
    
    # Check if cron job already exists
    local cron_comment="# Goose log rotation cron job"
    if crontab -l 2>/dev/null | grep -q "$cron_comment"; then
        print_warning "Cron job already exists. Removing old entry..."
        crontab -l 2>/dev/null | grep -v "$cron_comment" | grep -v "$abs_wrapper_script" | crontab - || true
    fi
    
    # Add new cron job
    (crontab -l 2>/dev/null || true; echo "$CRON_SCHEDULE $abs_wrapper_script $cron_comment") | crontab -
    
    print_success "User-level cron job installed successfully"
    print_info "Schedule: $CRON_SCHEDULE"
    print_info "Wrapper script: $abs_wrapper_script"
    print_info "Cron log file: $CRON_LOG_FILE"
}

# Function to install system-level cron
install_system_cron() {
    local wrapper_script="$1"
    local abs_wrapper_script
    abs_wrapper_script=$(get_absolute_path "$wrapper_script")
    local cron_file="/etc/cron.d/goose-log-rotation"
    
    print_info "Installing system-level cron job..."
    
    # Check for root/sudo
    if [[ $EUID -ne 0 ]]; then
        print_error "System-level cron installation requires root privileges"
        print_info "Please run with sudo: sudo $0"
        exit 1
    fi
    
    # Create cron.d file
    cat > "$cron_file" <<EOF
# Goose log rotation cron job
# Generated by install-cron-log-rotation.sh
# Do not edit manually - regenerated on each installation

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

$CRON_SCHEDULE root $abs_wrapper_script
EOF

    chmod 644 "$cron_file"
    
    print_success "System-level cron job installed successfully"
    print_info "Schedule: $CRON_SCHEDULE"
    print_info "Cron file: $cron_file"
    print_info "Cron log file: $CRON_LOG_FILE"
}

# Function to show usage
show_usage() {
    cat <<EOF
Usage: $0 [OPTIONS]

Install automated log rotation cron job for Goose.

OPTIONS:
    -s, --schedule SCHEDULE    Cron schedule (default: "0 2 * * *" - daily at 2 AM)
    -t, --type TYPE            Installation type: user or system (default: user)
    -l, --log-dir DIR          Directory for cron log output (default: /tmp/goose-logs)
    -h, --help                 Show this help message

ENVIRONMENT VARIABLES:
    GOOSE_CRON_SCHEDULE        Cron schedule (e.g., "0 2 * * *")
    GOOSE_CRON_INSTALL_TYPE    Installation type: user or system
    GOOSE_CRON_LOG_DIR         Directory for cron log output
    LOG_DIR                    Log directory for rotation script
    GOOSE_LOG_*                Log rotation configuration (see rotate-logs.sh)

EXAMPLES:
    # Install user-level cron (daily at 2 AM)
    $0

    # Install user-level cron with custom schedule (daily at 3 AM)
    $0 --schedule "0 3 * * *"

    # Install system-level cron (requires sudo)
    sudo $0 --type system

    # Install with custom log directory
    $0 --log-dir /var/log/goose

CRON SCHEDULE FORMAT:
    Minute Hour Day Month Weekday
    *      *    *   *     *       (every minute)
    0      *    *   *     *       (every hour)
    0      2    *   *     *       (daily at 2 AM)
    0      2    *   *     0       (weekly on Sunday at 2 AM)
    0      2    1   *     *       (monthly on 1st at 2 AM)

EOF
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -s|--schedule)
            CRON_SCHEDULE="$2"
            shift 2
            ;;
        -t|--type)
            INSTALL_TYPE="$2"
            if [[ "$INSTALL_TYPE" != "user" && "$INSTALL_TYPE" != "system" ]]; then
                print_error "Invalid installation type: $INSTALL_TYPE (must be 'user' or 'system')"
                exit 1
            fi
            shift 2
            ;;
        -l|--log-dir)
            CRON_LOG_DIR="$2"
            CRON_LOG_FILE="$CRON_LOG_DIR/cron-rotation.log"
            shift 2
            ;;
        -h|--help)
            show_usage
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
done

# Main installation
main() {
    print_info "Goose Log Rotation Cron Installation"
    print_info "====================================="
    echo
    
    # Detect OS
    local os_type
    os_type=$(detect_os)
    if [[ "$os_type" == "unknown" ]]; then
        print_warning "Unknown OS type: $OSTYPE. Proceeding anyway..."
    else
        print_info "Detected OS: $os_type"
    fi
    
    # Check prerequisites
    check_rotate_script
    
    # Create wrapper script
    print_info "Creating cron wrapper script..."
    local wrapper_script
    wrapper_script=$(create_cron_wrapper)
    print_success "Wrapper script created: $wrapper_script"
    
    # Install cron job
    if [[ "$INSTALL_TYPE" == "system" ]]; then
        install_system_cron "$wrapper_script"
    else
        install_user_cron "$wrapper_script"
    fi
    
    echo
    print_success "Installation complete!"
    echo
    print_info "To verify the cron job:"
    if [[ "$INSTALL_TYPE" == "system" ]]; then
        print_info "  sudo cat /etc/cron.d/goose-log-rotation"
    else
        print_info "  crontab -l"
    fi
    echo
    print_info "To view cron execution logs:"
    print_info "  tail -f $CRON_LOG_FILE"
    echo
    print_info "To uninstall, run:"
    print_info "  $SCRIPT_DIR/uninstall-cron-log-rotation.sh"
}

# Run main if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
